In [2]:
with open("shakespeare.txt", encoding='utf-8') as f:
    text=f.read()

In [3]:
text[:10]

'First Citi'

In [12]:
chars=sorted(list(set(text)))
c2i={c:i for i,c in enumerate(chars)}
i2c={i:c for i,c in enumerate(chars)}
encoder = lambda string: [c2i[c] for c in string]
decoder = lambda lst: ''.join([i2c[i] for i in lst])

encoder("hello")
decoder(encoder("hello how are you"))

'hello how are you'

In [13]:
import torch

data=torch.tensor(encoder(text))
data.shape, data.dtype

(torch.Size([1115394]), torch.int64)

In [14]:
n = int(0.9*len(data))
train_data, valid_data = data[:n], data[n:]

In [15]:
block_size=8

train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [16]:
x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range(block_size):
    context=x[:t+1]
    target=y[t]
    print(f"When input is {context} then target is {target}")

When input is tensor([18]) then target is 47
When input is tensor([18, 47]) then target is 56
When input is tensor([18, 47, 56]) then target is 57
When input is tensor([18, 47, 56, 57]) then target is 58
When input is tensor([18, 47, 56, 57, 58]) then target is 1
When input is tensor([18, 47, 56, 57, 58,  1]) then target is 15
When input is tensor([18, 47, 56, 57, 58,  1, 15]) then target is 47
When input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) then target is 58


In [19]:
20000*0.1/100

20.0

In [52]:
T=8
batch_size=4

def get_batch(batch_type):
    if batch_type=="train":
        data=train_data
    elif batch_type=="val":
        data=valid_data
    start_idx = torch.randint(0, data.size(0) - T - 1, (batch_size,))
    X=torch.stack([data[start_idx[i]:start_idx[i]+T] for i in range(batch_size)])
    y=torch.stack([data[start_idx[i]+1:start_idx[i]+T+1] for i in range(batch_size)])
    print(y)
    print(X)
    return X, y

get_batch("train")

    

tensor([[10,  0, 20, 47, 43,  1, 58, 53],
        [37,  1, 13, 26, 26, 17, 10,  0],
        [47, 58, 47, 64, 43, 52, 10,  0],
        [53, 44,  1, 39, 42, 51, 47, 56]])
tensor([[43, 10,  0, 20, 47, 43,  1, 58],
        [16, 37,  1, 13, 26, 26, 17, 10],
        [15, 47, 58, 47, 64, 43, 52, 10],
        [ 1, 53, 44,  1, 39, 42, 51, 47]])


(tensor([[43, 10,  0, 20, 47, 43,  1, 58],
         [16, 37,  1, 13, 26, 26, 17, 10],
         [15, 47, 58, 47, 64, 43, 52, 10],
         [ 1, 53, 44,  1, 39, 42, 51, 47]]),
 tensor([[10,  0, 20, 47, 43,  1, 58, 53],
         [37,  1, 13, 26, 26, 17, 10,  0],
         [47, 58, 47, 64, 43, 52, 10,  0],
         [53, 44,  1, 39, 42, 51, 47, 56]]))

In [53]:
def estimate_loss():
    n=20
    losses=[]
    for i in range(n):
        X,y=get_batch("train")
        X_val, y_val=get_batch("val")
        #processed_data, loss= model(X)
    return torch.mean(losses)

    

In [51]:
my_str="My favorite activity is coding, my framework for analyzing the world is Statistics. When I get an algorithm working, it's magic!"
len(my_str)

128