In [1]:
import torch

In [7]:
torch.manual_seed(1337)
B,T,C=4,8,2
x=torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [9]:
xbow=torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev=x[b,:t+1] #(t,C)
        xbow[b,t]=torch.mean(xprev,0)
xbow.shape
xbow

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])

In [38]:
multmat=torch.triu(torch.ones((T,T)))#
print(multmat.sum(1))
multmat=(multmat/torch.sum(multmat,0)).T
multmat
print((multmat@x)[0])
print(xbow[0])
#(multmat@x).shape

tensor([8., 7., 6., 5., 4., 3., 2., 1.])
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])


In [63]:
a=torch.tril(torch.ones((T,T)))
#a=a/torch.sum(a,1)
torch.sum(a,1,keepdim=True)
a=a/torch.sum(a,1,keepdim=True)
a

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [64]:
wei=torch.tril(torch.ones((T,T)))
wei=wei/torch.sum(wei,1,keepdim=True)
xbow2=(wei@x)
print(xbow2)

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])


In [70]:
tril=torch.tril(torch.ones((T,T)))
wei=torch.zeros((T,T))
wei=wei.masked_fill(tril==0, float('-inf'))
wei
wei=torch.nn.functional.softmax(wei,1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [83]:
#Let's implement self-attention
B,T,C=4,8,32

x=torch.randn(B,T,C)


class SelfAttention(torch.nn.Module):
    def __init__(self):
        super(SelfAttention, self).__init__()
        self.Q_linear=torch.nn.Linear(C,C,bias=False)
        self.K_linear=torch.nn.Linear(C,C,bias=False)
        self.V_linear=torch.nn.Linear(C,C,bias=False)

    def forward(self,x):
        Q=self.Q_linear(x)  
        K=self.K_linear(x)
        V=self.V_linear(x)
        #for b in range(B):
            #print(Q[b]@K[b].T)
        wei = torch.nn.functional.softmax(torch.bmm(Q, K.transpose(1, 2)),dim=2)
        print('value vec: ', torch.bmm(wei,V).shape)   
        return torch.bmm(wei,V)


sa=SelfAttention()
sa(x)


value vec:  torch.Size([4, 8, 32])


tensor([[[-0.2995, -0.1094, -0.1128,  ..., -0.4096,  0.2465,  0.2027],
         [-0.3415,  0.6291,  0.3136,  ..., -0.4373,  0.2854, -0.0337],
         [-0.1199,  0.0629,  0.0397,  ..., -0.1505,  0.1627,  0.0887],
         ...,
         [ 0.0169, -0.1011,  0.1028,  ..., -0.1999,  0.1021,  0.0268],
         [ 0.3011,  0.0338, -0.1095,  ...,  1.1276, -0.7868, -0.1009],
         [-0.0928,  0.0898, -0.0869,  ..., -0.1779,  0.2235, -0.0851]],

        [[ 1.1559,  0.4672,  0.0164,  ...,  0.9784, -1.1849,  0.1425],
         [ 0.6249,  0.2133,  0.2003,  ...,  0.6576, -0.7317,  0.0247],
         [-0.0698,  0.0612,  0.3269,  ..., -0.0109, -0.0206, -0.5223],
         ...,
         [ 0.1051, -0.2871,  0.3040,  ...,  0.5272, -0.5171,  0.4236],
         [ 0.1604, -0.3717,  0.0207,  ...,  0.7063, -0.6729,  0.4006],
         [-0.1056,  0.1657,  0.5304,  ..., -0.0852,  0.0699, -0.5669]],

        [[ 0.1406, -0.0884,  0.1732,  ...,  0.3883, -0.5387, -0.2160],
         [ 0.0637, -0.4132, -0.0897,  ...,  0

In [95]:
class MultiHeadAttention(torch.nn.Module):
    def __init__(self):
        super(MultiHeadAttention, self).__init__()
        self.H=12
        self.d_head=C//self.H
        self.QKV_linear=torch.nn.Linear(C,C*3,bias=False)

    def forward(self,x):
        QKV=self.QKV_linear(x)
        Q, K, V = QKV.chunk(3, dim=-1)
        Q=Q.view(B,T,self.H,self.d_head).transpose(1,2)
        K=K.view(B,T,self.H,self.d_head).transpose(1,2)
        V=V.view(B,T,self.H,self.d_head).transpose(1,2)
        scores = torch.matmul(Q, K.transpose(-2, -1)) / (self.d_head ** 0.5)
        weights = torch.nn.functional.softmax(scores, dim=-1)  # Shape: [B, H, T, T]

        # Weighted sum of values
        out = torch.matmul(weights, V)  # Shape: [B, H, T, d_head]

        # Concatenate heads and project back to the original dimension
        out = out.transpose(1, 2).contiguous().view(B, T, C)
        print(out.shape)
        return out
    
B,T,C=4,8,768

x=torch.randn(B,T,C)
ma=MultiHeadAttention()
ma(x)

torch.Size([4, 8, 768])


tensor([[[-0.0412, -0.0926,  0.0791,  ...,  0.2176,  0.1817, -0.3167],
         [-0.0489, -0.0241,  0.1201,  ...,  0.2884,  0.2653, -0.1681],
         [-0.0467, -0.0054,  0.1355,  ...,  0.2961,  0.0796, -0.3560],
         ...,
         [ 0.0204,  0.0401,  0.2390,  ...,  0.1231,  0.2492, -0.3457],
         [-0.0357, -0.0333,  0.1248,  ...,  0.1390,  0.2257, -0.2702],
         [-0.1059, -0.0265,  0.1538,  ...,  0.2043,  0.0707, -0.2855]],

        [[ 0.0239,  0.1958,  0.0060,  ..., -0.0083,  0.2584,  0.0264],
         [-0.0884,  0.1171,  0.1170,  ...,  0.0911,  0.1067,  0.1169],
         [-0.0454,  0.0857,  0.0811,  ...,  0.1771,  0.0578, -0.0026],
         ...,
         [-0.0152,  0.1237,  0.1097,  ...,  0.1490,  0.1103,  0.0398],
         [-0.0291,  0.1504,  0.0475,  ...,  0.1289,  0.1215,  0.0219],
         [-0.0508,  0.0652,  0.1009,  ...,  0.0225,  0.1713,  0.0539]],

        [[-0.0954, -0.0644,  0.3255,  ..., -0.0803,  0.3177,  0.0189],
         [-0.0906, -0.1257,  0.2720,  ...,  0

In [96]:
print(torch.cuda.is_available())

False


/home/maria/andrej-karpathy-experiments/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
